// ささえ愛用のテーブル名定数
export const TABLES = {
  PROFILES: "sasaeai_profiles",
  PROFILE_DETAILS: "sasaeai_profile_details",
  PROFILE_TAGS: "sasaeai_profile_tags",
  PROFILE_PHOTOS: "sasaeai_profile_photos",
  LIKES: "sasaeai_likes",
  MATCHES: "sasaeai_matches",
  MESSAGES: "sasaeai_messages",
  CONVERSATIONS: "sasaeai_conversations",
  SUBSCRIPTIONS: "sasaeai_subscriptions",
  COUPON_CODES: "sasaeai_coupon_codes",
  COUPON_USAGE: "sasaeai_coupon_usage",
  REPORTS: "sasaeai_reports",
  MODERATION_LOGS: "sasaeai_moderation_logs",
  SUSPENSION_HISTORY: "sasaeai_suspension_history",
  NOTIFICATIONS: "sasaeai_notifications",
  BLOCKS: "sasaeai_blocks",
  BLOCKED_USERS: "sasaeai_blocked_users",
  BANS: "sasaeai_bans",
  PROFILE_VIEWS: "sasaeai_profile_views",
  EMAIL_LOGS: "sasaeai_email_logs",
  EMAIL_SETTINGS: "sasaeai_email_settings",
  GROUP_CHAT_ROOMS: "sasaeai_group_chat_rooms",
  GROUP_CHAT_MESSAGES: "sasaeai_group_chat_messages",
  GROUP_CHAT_PARTICIPANTS: "sasaeai_group_chat_participants",
  SUSPENSIONS: "sasaeai_suspensions",
  WARNINGS: "sasaeai_warnings",
  PUSH_SUBSCRIPTIONS: "sasaeai_push_subscriptions",
  ADMIN_NOTIFICATION_SETTINGS: "sasaeai_admin_notification_settings",
  PAYMENTS: "sasaeai_payments",
} as const

export const TABLE_NAMES = TABLES
